twig:
#    default_path: '%kernel.project_dir%/templates/tailwind'
    file_name_pattern: '*.twig'
    globals:
        menu_service: '@App\Service\MenuBuilderService'
    form_themes:
        - 'form/combo_box.html.twig'
        - '@EasyAdmin/crud/form_theme.html.twig'

when@test:
    twig:
        strict_variables: true
